version: "2"
run:
  issues-exit-code: 1
  tests: false
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*testing.T).Log
        - (*testing.T).Logf
        - (*testing.T).Error
        - (*testing.T).Errorf
        - (*testing.B).Log
        - (*testing.B).Logf
        - (*testing.B).Error
        - (*testing.B).Errorf
    gosec:
      includes:
        - G101
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G201
        - G202
        - G203
        - G204
        - G301
        - G302
        - G303
        - G304
        - G305
        - G306
        - G307
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505
      excludes:
        - G104
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - funlen
          - gocritic
          - gocyclo
          - gosec
        path: _benchmark_test\.go
    paths:
      - vendor
      - .git
      - bin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - .git
      - bin
      - third_party$
      - builtin$
      - examples$
